# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _google/protobuf/internal/test_bad_identifiers.proto
"""Generated protocol buffer code."""
from _google.protobuf.internal import builder as _builder
from _google.protobuf import descriptor as _descriptor
from _google.protobuf import descriptor_pool as _descriptor_pool
from _google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4_google/protobuf/internal/test_bad_identifiers.proto\x12\x11protobuf_unittest\"\x1e\n\x12TestBadIdentifiers*\x08\x08\x64\x10\x80\x80\x80\x80\x02\"\x10\n\x0e\x41notherMessage2\x10\n\x0e\x41notherService:;\n\x07message\x12%.protobuf_unittest.TestBadIdentifiers\x18\x64 \x01(\t:\x03\x66oo:>\n\ndescriptor\x12%.protobuf_unittest.TestBadIdentifiers\x18\x65 \x01(\t:\x03\x62\x61r:>\n\nreflection\x12%.protobuf_unittest.TestBadIdentifiers\x18\x66 \x01(\t:\x03\x62\x61z:;\n\x07service\x12%.protobuf_unittest.TestBadIdentifiers\x18g \x01(\t:\x03quxB\x03\x90\x01\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, '_google.protobuf.internal.test_bad_identifiers_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  TestBadIdentifiers.RegisterExtension(message)
  TestBadIdentifiers.RegisterExtension(descriptor)
  TestBadIdentifiers.RegisterExtension(reflection)
  TestBadIdentifiers.RegisterExtension(service)

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\220\001\001'
  _TESTBADIDENTIFIERS._serialized_start=75
  _TESTBADIDENTIFIERS._serialized_end=105
  _ANOTHERMESSAGE._serialized_start=107
  _ANOTHERMESSAGE._serialized_end=123
  _ANOTHERSERVICE._serialized_start=125
  _ANOTHERSERVICE._serialized_end=141
_builder.BuildServices(DESCRIPTOR, '_google.protobuf.internal.test_bad_identifiers_pb2', globals())
# @@protoc_insertion_point(module_scope)
