# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _google/protobuf/internal/import_test_package/import_public.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from _google.protobuf.internal.import_test_package import import_public_nested_pb2 as __google_dot_protobuf_dot_internal_dot_import__test__package_dot_import__public__nested__pb2

from _google.protobuf.internal.import_test_package.import_public_nested_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nA_google/protobuf/internal/import_test_package/import_public.proto\x12\x33google.protobuf.python.internal.import_test_package\x1aH_google/protobuf/internal/import_test_package/import_public_nested.protoB\x02H\x01P\x00')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, '_google.protobuf.internal.import_test_package.import_public_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
# @@protoc_insertion_point(module_scope)
